### ISSUE TITLE
1.0.1 release: TypeError: Cannot read property 'done' of undefined 

### ISSUE THREAD

**Issue by cristianiorga** [Appius/dts-bundle-webpack#2]
The latest 1.0.1 release gives the following error:

```
C:\git\MyApp\Packages\mypackage\node_modules\webpack\bin\webpack.js:348
                        throw err;
                        ^

TypeError: Cannot read property 'done' of undefined
    at DtsBundlePlugin.apply (C:\git\MyApp\Packages\mypackage\node_modules\dts-bundle-webpack\index.js:13:24)
    at Compiler.apply (C:\git\MyApp\Packages\mypackage\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (C:\git\MyApp\Packages\mypackage\node_modules\webpack\lib\webpack.js:33:19)
    at processOptions (C:\git\MyApp\Packages\mypackage\node_modules\webpack\bin\webpack.js:335:15)
    at yargs.parse (C:\git\MyApp\Packages\mypackage\node_modules\webpack\bin\webpack.js:397:2)
    at Object.Yargs.self.parse (C:\git\MyApp\Packages\mypackage\node_modules\yargs\yargs.js:533:18)
    at Object.<anonymous> (C:\git\MyApp\Packages\mypackage\node_modules\webpack\bin\webpack.js:152:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
```
Configuration:
```
  plugins: [
    new CleanWebpackPlugin([outputPathName]),
    new DtsBundleWebpack({
      name: packageName.replace('/','-'),
      main: outputPathName + "/**/*.d.ts",
      removeSource: true,
      out: "index.d.ts",
      outputAsModuleFolder: true
    }),
    new webpack.optimize.UglifyJsPlugin({})
  ]
```

**Comment by Appius** [comment]
thanks! fixed with version 1.0.2
